/* ==================================== JUCER_BINARY_RESOURCE ====================================

   This is an auto-generated file: Any edits you make may be overwritten!

*/

namespace BinaryData
{

//================== WeirdInstrument.xml ==================
static const unsigned char temp_binary_data_0[] =
"<App>\n"
"\t <Instrument id=\"i0\">\n"
"\t \t <Resonator id=\"i0_r0\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r0_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_T\" value=\"669.864\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r0_o0\" channel=\"2\" loc=\"100\"/>\n"
"\t \t \t <Output id=\"i0_r0_o1\" channel=\"2\" loc=\"4\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r1\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r1_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_T\" value=\"1193.62\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r1_o0\" channel=\"2\" loc=\"6\"/>\n"
"\t \t \t <Output id=\"i0_r1_o1\" channel=\"2\" loc=\"84\"/>\n"
"\t \t \t <Output id=\"i0_r1_o2\" channel=\"2\" loc=\"61\"/>\n"
"\t \t \t <Output id=\"i0_r1_o3\" channel=\"2\" loc=\"52\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r2\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r2_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_T\" value=\"29998\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_A\" value=\"7.85398e-05\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_I\" value=\"4.90874e-10\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r2_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r2_o1\" channel=\"2\" loc=\"37\"/>\n"
"\t \t \t <Output id=\"i0_r2_o2\" channel=\"2\" loc=\"28\"/>\n"
"\t \t \t <Output id=\"i0_r2_o3\" channel=\"2\" loc=\"20\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r3\" type=\"Thin_Plate\">\n"
"\t \t \t <PARAM id=\"i0_r3_Lx\" value=\"0.75\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_Ly\" value=\"0.25\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_H\" value=\"0.005\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_nu\" value=\"0.3\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_sig1\" value=\"0.005\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_maxPoints\" value=\"2000\"/>\n"
"\t \t \t <Output id=\"i0_r3_o0\" channel=\"0\" loc=\"145\"/>\n"
"\t \t \t <Output id=\"i0_r3_o1\" channel=\"1\" loc=\"163\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Connection id=\"i0_c0\" type=\"nonlinear\">\n"
"\t \t \t <PARAM id=\"i0_c0_fR\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_c0_fL\" value=\"50\"/>\n"
"\t \t \t <PARAM id=\"i0_c0_tR\" value=\"2\"/>\n"
"\t \t \t <PARAM id=\"i0_c0_tL\" value=\"18\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c1\" type=\"nonlinear\">\n"
"\t \t \t <PARAM id=\"i0_c1_fR\" value=\"0\"/>\n"
"\t \t \t <PARAM id=\"i0_c1_fL\" value=\"37\"/>\n"
"\t \t \t <PARAM id=\"i0_c1_tR\" value=\"2\"/>\n"
"\t \t \t <PARAM id=\"i0_c1_tL\" value=\"25\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c2\" type=\"nonlinear\">\n"
"\t \t \t <PARAM id=\"i0_c2_fR\" value=\"0\"/>\n"
"\t \t \t <PARAM id=\"i0_c2_fL\" value=\"25\"/>\n"
"\t \t \t <PARAM id=\"i0_c2_tR\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_c2_tL\" value=\"64\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c3\" type=\"nonlinear\">\n"
"\t \t \t <PARAM id=\"i0_c3_fR\" value=\"0\"/>\n"
"\t \t \t <PARAM id=\"i0_c3_fL\" value=\"65\"/>\n"
"\t \t \t <PARAM id=\"i0_c3_tR\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_c3_tL\" value=\"20\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c4\" type=\"nonlinear\">\n"
"\t \t \t <PARAM id=\"i0_c4_fR\" value=\"2\"/>\n"
"\t \t \t <PARAM id=\"i0_c4_fL\" value=\"22\"/>\n"
"\t \t \t <PARAM id=\"i0_c4_tR\" value=\"3\"/>\n"
"\t \t \t <PARAM id=\"i0_c4_tL\" value=\"151\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c5\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c5_fR\" value=\"2\"/>\n"
"\t \t \t <PARAM id=\"i0_c5_fL\" value=\"30\"/>\n"
"\t \t \t <PARAM id=\"i0_c5_tR\" value=\"3\"/>\n"
"\t \t \t <PARAM id=\"i0_c5_tL\" value=\"190\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c6\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c6_fR\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_c6_fL\" value=\"71\"/>\n"
"\t \t \t <PARAM id=\"i0_c6_tR\" value=\"2\"/>\n"
"\t \t \t <PARAM id=\"i0_c6_tL\" value=\"27\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c7\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c7_fR\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_c7_fL\" value=\"57\"/>\n"
"\t \t \t <PARAM id=\"i0_c7_tR\" value=\"3\"/>\n"
"\t \t \t <PARAM id=\"i0_c7_tL\" value=\"158\"/>\n"
"\t \t </Connection>\n"
"\t </Instrument>\n"
"</App>\n";

const char* WeirdInstrument_xml = (const char*) temp_binary_data_0;

//================== Harp.xml ==================
static const unsigned char temp_binary_data_1[] =
"<App>\n"
"\t <Instrument id=\"i0\">\n"
"\t \t <Resonator id=\"i0_r0\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r0_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_T\" value=\"421.989\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r0_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r0_o1\" channel=\"2\" loc=\"109\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r1\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r1_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_T\" value=\"531.679\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r1_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r1_o1\" channel=\"2\" loc=\"105\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r2\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r2_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_T\" value=\"669.864\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r2_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r2_o1\" channel=\"2\" loc=\"100\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r3\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r3_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_T\" value=\"751.896\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r3_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r3_o1\" channel=\"2\" loc=\"97\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r4\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r4_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_T\" value=\"947.396\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r4_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r4_o1\" channel=\"2\" loc=\"91\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r5\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r5_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_T\" value=\"1193.62\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r5_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r5_o1\" channel=\"2\" loc=\"85\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r6\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r6_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_T\" value=\"1503.84\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r6_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r6_o1\" channel=\"2\" loc=\"78\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r7\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r7_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_T\" value=\"1688.09\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r7_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r7_o1\" channel=\"2\" loc=\"74\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r8\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r8_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r8_T\" value=\"2126.71\"/>\n"
"\t \t \t <PARAM id=\"i0_r8_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r8_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r8_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r8_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r8_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r8_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r8_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r8_o1\" channel=\"2\" loc=\"67\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r9\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r9_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r9_T\" value=\"2679.62\"/>\n"
"\t \t \t <PARAM id=\"i0_r9_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r9_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r9_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r9_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r9_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r9_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r9_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r9_o1\" channel=\"2\" loc=\"60\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r10\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r10_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r10_T\" value=\"3007.76\"/>\n"
"\t \t \t <PARAM id=\"i0_r10_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r10_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r10_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r10_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r10_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r10_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r10_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r10_o1\" channel=\"2\" loc=\"57\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r11\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r11_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r11_T\" value=\"3789.58\"/>\n"
"\t \t \t <PARAM id=\"i0_r11_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r11_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r11_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r11_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r11_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r11_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r11_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r11_o1\" channel=\"2\" loc=\"51\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r12\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r12_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r12_T\" value=\"4774.47\"/>\n"
"\t \t \t <PARAM id=\"i0_r12_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r12_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r12_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r12_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r12_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r12_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r12_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r12_o1\" channel=\"2\" loc=\"45\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r13\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r13_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r13_T\" value=\"6015.37\"/>\n"
"\t \t \t <PARAM id=\"i0_r13_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r13_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r13_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r13_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r13_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r13_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r13_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r13_o1\" channel=\"2\" loc=\"40\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r14\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r14_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r14_T\" value=\"6752.09\"/>\n"
"\t \t \t <PARAM id=\"i0_r14_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r14_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r14_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r14_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r14_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r14_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r14_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r14_o1\" channel=\"2\" loc=\"37\"/>\n"
"\t \t </Resonator>\n"
"\t </Instrument>\n"
"</App>\n";

const char* Harp_xml = (const char*) temp_binary_data_1;

//================== TwoStringsOctave.xml ==================
static const unsigned char temp_binary_data_2[] =
"<App>\n"
"\t <Instrument id=\"i0\">\n"
"\t \t <Resonator id=\"i0_r0\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r0_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_T\" value=\"298.404\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r0_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r0_o1\" channel=\"2\" loc=\"114\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r1\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r1_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_T\" value=\"1193.62\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r1_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r1_o1\" channel=\"2\" loc=\"85\"/>\n"
"\t \t </Resonator>\n"
"\t </Instrument>\n"
"</App>\n";

const char* TwoStringsOctave_xml = (const char*) temp_binary_data_2;

//================== guitar.xml ==================
static const unsigned char temp_binary_data_3[] =
"<App>\n"
"\t <Instrument id=\"i0\">\n"
"\t \t <Resonator id=\"i0_r0\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r0_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_T\" value=\"669.864\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig1\" value=\"0.005\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r1\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r1_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_T\" value=\"1193.62\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_sig1\" value=\"0.005\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r2\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r2_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_T\" value=\"2126.71\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_sig1\" value=\"0.005\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r3\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r3_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_T\" value=\"3789.59\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_sig1\" value=\"0.005\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r4\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r4_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_T\" value=\"6015.37\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_sig1\" value=\"0.005\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r5\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r5_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_T\" value=\"10718.1\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_sig1\" value=\"0.005\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r6\" type=\"Bar\">\n"
"\t \t \t <PARAM id=\"i0_r6_L\" value=\"0.5\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_rho\" value=\"1190\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_A\" value=\"2.0175e-05\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_E\" value=\"3.2e+09\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_I\" value=\"9.45703e-11\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_sig1\" value=\"0.05\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r7\" type=\"Thin_Plate\">\n"
"\t \t \t <PARAM id=\"i0_r7_Lx\" value=\"0.75\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_Ly\" value=\"0.25\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_rho\" value=\"1150\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_H\" value=\"0.005\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_E\" value=\"3.8e+09\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_nu\" value=\"0.3\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_sig1\" value=\"0.05\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_maxPoints\" value=\"2000\"/>\n"
"\t \t \t <Output id=\"i0_r7_o0\" channel=\"2\" locX=\"0.104167\" locY=\"0.125\"/>\n"
"\t \t \t <Output id=\"i0_r7_o1\" channel=\"2\" locX=\"0.0625\" locY=\"0.1875\"/>\n"
"\t \t \t <Output id=\"i0_r7_o2\" channel=\"2\" locX=\"0.125\" locY=\"0.3125\"/>\n"
"\t \t \t <Output id=\"i0_r7_o3\" channel=\"2\" locX=\"0.125\" locY=\"0.5625\"/>\n"
"\t \t \t <Output id=\"i0_r7_o4\" channel=\"2\" locX=\"0.0625\" locY=\"0.4375\"/>\n"
"\t \t \t <Output id=\"i0_r7_o5\" channel=\"2\" locX=\"0.0625\" locY=\"0.6875\"/>\n"
"\t \t \t <Output id=\"i0_r7_o6\" channel=\"2\" locX=\"0.0833333\" locY=\"0.8125\"/>\n"
"\t \t \t <Output id=\"i0_r7_o7\" channel=\"2\" locX=\"0.125\" locY=\"0.8125\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Connection id=\"i0_c0\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c0_fR\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_c0_fL\" value=\"0.977778\"/>\n"
"\t \t \t <PARAM id=\"i0_c0_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c0_fL\" value=\"0.230769\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c1\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c1_fR\" value=\"2\"/>\n"
"\t \t \t <PARAM id=\"i0_c1_fL\" value=\"0.972222\"/>\n"
"\t \t \t <PARAM id=\"i0_c1_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c1_fL\" value=\"0.384615\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c2\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c2_fR\" value=\"3\"/>\n"
"\t \t \t <PARAM id=\"i0_c2_fL\" value=\"0.964286\"/>\n"
"\t \t \t <PARAM id=\"i0_c2_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c2_fL\" value=\"0.564103\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c3\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c3_fR\" value=\"4\"/>\n"
"\t \t \t <PARAM id=\"i0_c3_fL\" value=\"0.955556\"/>\n"
"\t \t \t <PARAM id=\"i0_c3_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c3_fL\" value=\"0.717949\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c4\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c4_fR\" value=\"5\"/>\n"
"\t \t \t <PARAM id=\"i0_c4_fL\" value=\"0.941176\"/>\n"
"\t \t \t <PARAM id=\"i0_c4_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c4_fL\" value=\"0.871795\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c5\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c5_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c5_fL\" value=\"0.15\"/>\n"
"\t \t \t <PARAM id=\"i0_c5_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c5_tL\" valueX=\"0.104167 \" valueY=\"0.25\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c6\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c6_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c6_fL\" value=\"0.25\"/>\n"
"\t \t \t <PARAM id=\"i0_c6_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c6_tL\" valueX=\"0.0833333 \" valueY=\"0.3125\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c7\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c7_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c7_fL\" value=\"0.6\"/>\n"
"\t \t \t <PARAM id=\"i0_c7_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c7_tL\" valueX=\"0.0833333 \" valueY=\"0.5625\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c8\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c8_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c8_fL\" value=\"0.9\"/>\n"
"\t \t \t <PARAM id=\"i0_c8_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c8_tL\" valueX=\"0.104167 \" valueY=\"0.75\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c9\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c9_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c9_fL\" value=\"0.8\"/>\n"
"\t \t \t <PARAM id=\"i0_c9_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c9_tL\" valueX=\"0.0833333 \" valueY=\"0.6875\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c10\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c10_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c10_fL\" value=\"0.675\"/>\n"
"\t \t \t <PARAM id=\"i0_c10_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c10_tL\" valueX=\"0.104167 \" valueY=\"0.625\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c11\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c11_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c11_fL\" value=\"0.5\"/>\n"
"\t \t \t <PARAM id=\"i0_c11_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c11_tL\" valueX=\"0.104167 \" valueY=\"0.5\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c12\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c12_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c12_fL\" value=\"0.425\"/>\n"
"\t \t \t <PARAM id=\"i0_c12_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c12_tL\" valueX=\"0.0833333 \" valueY=\"0.4375\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c13\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c13_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c13_fL\" value=\"0.1\"/>\n"
"\t \t \t <PARAM id=\"i0_c13_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c13_tL\" valueX=\"0.0833333 \" valueY=\"0.1875\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c14\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c14_fR\" value=\"0\"/>\n"
"\t \t \t <PARAM id=\"i0_c14_fL\" value=\"0.980952\"/>\n"
"\t \t \t <PARAM id=\"i0_c14_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c14_fL\" value=\"0.128205\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c15\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c15_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c15_fL\" value=\"0.325\"/>\n"
"\t \t \t <PARAM id=\"i0_c15_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c15_tL\" valueX=\"0.104167 \" valueY=\"0.375\"/>\n"
"\t \t </Connection>\n"
"\t </Instrument>\n"
"</App>\n";

const char* guitar_xml = (const char*) temp_binary_data_3;

//================== EmptyInstrument.xml ==================
static const unsigned char temp_binary_data_4[] =
"<App>\n"
"\t <Instrument id=\"i0\">\n"
"\t </Instrument>\n"
"</App>\n";

const char* EmptyInstrument_xml = (const char*) temp_binary_data_4;


const char* getNamedResource (const char* resourceNameUTF8, int& numBytes);
const char* getNamedResource (const char* resourceNameUTF8, int& numBytes)
{
    unsigned int hash = 0;

    if (resourceNameUTF8 != nullptr)
        while (*resourceNameUTF8 != 0)
            hash = 31 * hash + (unsigned int) *resourceNameUTF8++;

    switch (hash)
    {
        case 0x4dbaafcc:  numBytes = 4109; return WeirdInstrument_xml;
        case 0x0b70d0ef:  numBytes = 7820; return Harp_xml;
        case 0xf867b85e:  numBytes = 1081; return TwoStringsOctave_xml;
        case 0x4c7b0ae2:  numBytes = 7737; return guitar_xml;
        case 0x5317664c:  numBytes = 52; return EmptyInstrument_xml;
        default: break;
    }

    numBytes = 0;
    return nullptr;
}

const char* namedResourceList[] =
{
    "WeirdInstrument_xml",
    "Harp_xml",
    "TwoStringsOctave_xml",
    "guitar_xml",
    "EmptyInstrument_xml"
};

const char* originalFilenames[] =
{
    "WeirdInstrument.xml",
    "Harp.xml",
    "TwoStringsOctave.xml",
    "guitar.xml",
    "EmptyInstrument.xml"
};

const char* getNamedResourceOriginalFilename (const char* resourceNameUTF8);
const char* getNamedResourceOriginalFilename (const char* resourceNameUTF8)
{
    for (unsigned int i = 0; i < (sizeof (namedResourceList) / sizeof (namedResourceList[0])); ++i)
    {
        if (namedResourceList[i] == resourceNameUTF8)
            return originalFilenames[i];
    }

    return nullptr;
}

}
