/* ==================================== JUCER_BINARY_RESOURCE ====================================

   This is an auto-generated file: Any edits you make may be overwritten!

*/

namespace BinaryData
{

//================== EmptyInstrument.xml ==================
static const unsigned char temp_binary_data_0[] =
"<App>\n"
"\t <Instrument id=\"i0\">\n"
"\t </Instrument>\n"
"</App>\n";

const char* EmptyInstrument_xml = (const char*) temp_binary_data_0;

//================== guitar.xml ==================
static const unsigned char temp_binary_data_1[] =
"<App>\n"
"\t <Instrument id=\"i0\">\n"
"\t \t <Resonator id=\"i0_r0\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r0_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_T\" value=\"669.864\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig1\" value=\"0.005\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r1\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r1_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_T\" value=\"1193.62\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_sig1\" value=\"0.005\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r2\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r2_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_T\" value=\"2126.71\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_sig1\" value=\"0.005\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r3\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r3_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_T\" value=\"3789.59\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_sig1\" value=\"0.005\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r4\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r4_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_T\" value=\"6015.37\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_sig1\" value=\"0.005\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r5\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r5_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_T\" value=\"10718.1\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_sig1\" value=\"0.005\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r6\" type=\"Bar\">\n"
"\t \t \t <PARAM id=\"i0_r6_L\" value=\"0.5\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_rho\" value=\"1190\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_A\" value=\"2.0175e-05\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_E\" value=\"3.2e+09\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_I\" value=\"9.45703e-11\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_sig1\" value=\"0.05\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r7\" type=\"Thin_Plate\">\n"
"\t \t \t <PARAM id=\"i0_r7_Lx\" value=\"0.75\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_Ly\" value=\"0.25\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_rho\" value=\"1150\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_H\" value=\"0.005\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_E\" value=\"3.8e+09\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_nu\" value=\"0.3\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_sig1\" value=\"0.05\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_maxPoints\" value=\"2000\"/>\n"
"\t \t \t <Output id=\"i0_r7_o0\" channel=\"2\" loc=\"99\"/>\n"
"\t \t \t <Output id=\"i0_r7_o1\" channel=\"2\" loc=\"144\"/>\n"
"\t \t \t <Output id=\"i0_r7_o2\" channel=\"2\" loc=\"241\"/>\n"
"\t \t \t <Output id=\"i0_r7_o3\" channel=\"2\" loc=\"429\"/>\n"
"\t \t \t <Output id=\"i0_r7_o4\" channel=\"2\" loc=\"332\"/>\n"
"\t \t \t <Output id=\"i0_r7_o5\" channel=\"2\" loc=\"520\"/>\n"
"\t \t \t <Output id=\"i0_r7_o6\" channel=\"2\" loc=\"615\"/>\n"
"\t \t \t <Output id=\"i0_r7_o7\" channel=\"2\" loc=\"617\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Connection id=\"i0_c0\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c0_fR\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_c0_fL\" value=\"88\"/>\n"
"\t \t \t <PARAM id=\"i0_c0_tR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c0_tL\" value=\"9\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c1\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c1_fR\" value=\"2\"/>\n"
"\t \t \t <PARAM id=\"i0_c1_fL\" value=\"70\"/>\n"
"\t \t \t <PARAM id=\"i0_c1_tR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c1_tL\" value=\"15\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c2\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c2_fR\" value=\"3\"/>\n"
"\t \t \t <PARAM id=\"i0_c2_fL\" value=\"54\"/>\n"
"\t \t \t <PARAM id=\"i0_c2_tR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c2_tL\" value=\"22\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c3\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c3_fR\" value=\"4\"/>\n"
"\t \t \t <PARAM id=\"i0_c3_fL\" value=\"43\"/>\n"
"\t \t \t <PARAM id=\"i0_c3_tR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c3_tL\" value=\"28\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c4\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c4_fR\" value=\"5\"/>\n"
"\t \t \t <PARAM id=\"i0_c4_fL\" value=\"32\"/>\n"
"\t \t \t <PARAM id=\"i0_c4_tR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c4_tL\" value=\"34\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c5\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c5_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c5_fL\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c5_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c5_tL\" value=\"193\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c6\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c6_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c6_fL\" value=\"10\"/>\n"
"\t \t \t <PARAM id=\"i0_c6_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c6_tL\" value=\"239\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c7\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c7_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c7_fL\" value=\"24\"/>\n"
"\t \t \t <PARAM id=\"i0_c7_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c7_tL\" value=\"427\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c8\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c8_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c8_fL\" value=\"36\"/>\n"
"\t \t \t <PARAM id=\"i0_c8_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c8_tL\" value=\"569\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c9\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c9_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c9_fL\" value=\"32\"/>\n"
"\t \t \t <PARAM id=\"i0_c9_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c9_tL\" value=\"521\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c10\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c10_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c10_fL\" value=\"27\"/>\n"
"\t \t \t <PARAM id=\"i0_c10_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c10_tL\" value=\"475\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c11\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c11_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c11_fL\" value=\"20\"/>\n"
"\t \t \t <PARAM id=\"i0_c11_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c11_tL\" value=\"381\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c12\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c12_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c12_fL\" value=\"17\"/>\n"
"\t \t \t <PARAM id=\"i0_c12_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c12_tL\" value=\"333\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c13\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c13_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c13_fL\" value=\"4\"/>\n"
"\t \t \t <PARAM id=\"i0_c13_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c13_tL\" value=\"145\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c14\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c14_fR\" value=\"0\"/>\n"
"\t \t \t <PARAM id=\"i0_c14_fL\" value=\"103\"/>\n"
"\t \t \t <PARAM id=\"i0_c14_tR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c14_tL\" value=\"5\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c15\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c15_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c15_fL\" value=\"13\"/>\n"
"\t \t \t <PARAM id=\"i0_c15_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c15_tL\" value=\"287\"/>\n"
"\t \t </Connection>\n"
"\t </Instrument>\n"
"</App>\n";

const char* guitar_xml = (const char*) temp_binary_data_1;

//================== GuitarWithoutBody.xml ==================
static const unsigned char temp_binary_data_2[] =
"<App>\n"
"\t <Instrument id=\"i0\">\n"
"\t \t <Resonator id=\"i0_r0\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r0_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_T\" value=\"669.864\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r0_o0\" channel=\"2\" loc=\"9\"/>\n"
"\t \t \t <Output id=\"i0_r0_o1\" channel=\"2\" loc=\"98\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r1\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r1_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_T\" value=\"1193.62\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r1_o0\" channel=\"2\" loc=\"7\"/>\n"
"\t \t \t <Output id=\"i0_r1_o1\" channel=\"2\" loc=\"83\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r2\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r2_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_T\" value=\"2126.71\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r2_o0\" channel=\"2\" loc=\"6\"/>\n"
"\t \t \t <Output id=\"i0_r2_o1\" channel=\"2\" loc=\"66\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r3\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r3_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_T\" value=\"3789.59\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r3_o0\" channel=\"2\" loc=\"3\"/>\n"
"\t \t \t <Output id=\"i0_r3_o1\" channel=\"2\" loc=\"51\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r4\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r4_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_T\" value=\"6015.37\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r4_o0\" channel=\"2\" loc=\"3\"/>\n"
"\t \t \t <Output id=\"i0_r4_o1\" channel=\"2\" loc=\"41\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r5\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r5_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_T\" value=\"10718.1\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r5_o0\" channel=\"2\" loc=\"3\"/>\n"
"\t \t \t <Output id=\"i0_r5_o1\" channel=\"2\" loc=\"31\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r6\" type=\"Bar\">\n"
"\t \t \t <PARAM id=\"i0_r6_L\" value=\"0.5\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_rho\" value=\"1190\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_A\" value=\"2.0175e-05\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_E\" value=\"3.2e+09\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_I\" value=\"9.45703e-11\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_sig1\" value=\"0.05\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Connection id=\"i0_c0\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c0_fR\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_c0_fL\" value=\"88\"/>\n"
"\t \t \t <PARAM id=\"i0_c0_tR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c0_tL\" value=\"9\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c1\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c1_fR\" value=\"2\"/>\n"
"\t \t \t <PARAM id=\"i0_c1_fL\" value=\"70\"/>\n"
"\t \t \t <PARAM id=\"i0_c1_tR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c1_tL\" value=\"15\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c2\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c2_fR\" value=\"3\"/>\n"
"\t \t \t <PARAM id=\"i0_c2_fL\" value=\"54\"/>\n"
"\t \t \t <PARAM id=\"i0_c2_tR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c2_tL\" value=\"22\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c3\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c3_fR\" value=\"4\"/>\n"
"\t \t \t <PARAM id=\"i0_c3_fL\" value=\"43\"/>\n"
"\t \t \t <PARAM id=\"i0_c3_tR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c3_tL\" value=\"28\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c4\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c4_fR\" value=\"5\"/>\n"
"\t \t \t <PARAM id=\"i0_c4_fL\" value=\"32\"/>\n"
"\t \t \t <PARAM id=\"i0_c4_tR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c4_tL\" value=\"34\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c5\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c5_fR\" value=\"0\"/>\n"
"\t \t \t <PARAM id=\"i0_c5_fL\" value=\"103\"/>\n"
"\t \t \t <PARAM id=\"i0_c5_tR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c5_tL\" value=\"5\"/>\n"
"\t \t </Connection>\n"
"\t </Instrument>\n"
"</App>\n";

const char* GuitarWithoutBody_xml = (const char*) temp_binary_data_2;

//================== Harp.xml ==================
static const unsigned char temp_binary_data_3[] =
"<App>\n"
"\t <Instrument id=\"i0\">\n"
"\t \t <Resonator id=\"i0_r0\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r0_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_T\" value=\"421.989\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r0_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r0_o1\" channel=\"2\" loc=\"109\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r1\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r1_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_T\" value=\"531.679\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r1_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r1_o1\" channel=\"2\" loc=\"105\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r2\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r2_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_T\" value=\"669.864\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r2_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r2_o1\" channel=\"2\" loc=\"100\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r3\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r3_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_T\" value=\"751.896\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r3_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r3_o1\" channel=\"2\" loc=\"97\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r4\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r4_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_T\" value=\"947.396\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r4_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r4_o1\" channel=\"2\" loc=\"91\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r5\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r5_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_T\" value=\"1193.62\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r5_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r5_o1\" channel=\"2\" loc=\"85\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r6\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r6_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_T\" value=\"1503.84\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r6_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r6_o1\" channel=\"2\" loc=\"78\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r7\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r7_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_T\" value=\"1688.09\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r7_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r7_o1\" channel=\"2\" loc=\"74\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r8\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r8_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r8_T\" value=\"2126.71\"/>\n"
"\t \t \t <PARAM id=\"i0_r8_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r8_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r8_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r8_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r8_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r8_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r8_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r8_o1\" channel=\"2\" loc=\"67\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r9\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r9_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r9_T\" value=\"2679.62\"/>\n"
"\t \t \t <PARAM id=\"i0_r9_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r9_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r9_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r9_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r9_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r9_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r9_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r9_o1\" channel=\"2\" loc=\"60\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r10\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r10_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r10_T\" value=\"3007.76\"/>\n"
"\t \t \t <PARAM id=\"i0_r10_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r10_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r10_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r10_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r10_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r10_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r10_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r10_o1\" channel=\"2\" loc=\"57\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r11\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r11_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r11_T\" value=\"3789.58\"/>\n"
"\t \t \t <PARAM id=\"i0_r11_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r11_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r11_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r11_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r11_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r11_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r11_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r11_o1\" channel=\"2\" loc=\"51\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r12\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r12_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r12_T\" value=\"4774.47\"/>\n"
"\t \t \t <PARAM id=\"i0_r12_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r12_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r12_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r12_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r12_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r12_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r12_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r12_o1\" channel=\"2\" loc=\"45\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r13\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r13_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r13_T\" value=\"6015.37\"/>\n"
"\t \t \t <PARAM id=\"i0_r13_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r13_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r13_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r13_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r13_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r13_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r13_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r13_o1\" channel=\"2\" loc=\"40\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r14\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r14_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r14_T\" value=\"6752.09\"/>\n"
"\t \t \t <PARAM id=\"i0_r14_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r14_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r14_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r14_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r14_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r14_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r14_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r14_o1\" channel=\"2\" loc=\"37\"/>\n"
"\t \t </Resonator>\n"
"\t </Instrument>\n"
"</App>\n";

const char* Harp_xml = (const char*) temp_binary_data_3;

//================== HarpGroups.xml ==================
static const unsigned char temp_binary_data_4[] =
"ouse<App>\n"
"\t <Instrument id=\"i0\">\n"
"\t \t <Resonator id=\"i0_r0\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r0_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_T\" value=\"421.989\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r0_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r0_o1\" channel=\"2\" loc=\"109\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r1\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r1_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_T\" value=\"531.679\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r1_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r1_o1\" channel=\"2\" loc=\"105\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r2\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r2_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_T\" value=\"669.864\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r2_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r2_o1\" channel=\"2\" loc=\"100\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r3\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r3_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_T\" value=\"751.896\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r3_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r3_o1\" channel=\"2\" loc=\"97\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r4\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r4_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_T\" value=\"947.396\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r4_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r4_o1\" channel=\"2\" loc=\"91\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r5\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r5_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_T\" value=\"1193.62\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r5_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r5_o1\" channel=\"2\" loc=\"85\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r6\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r6_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_T\" value=\"1503.84\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r6_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r6_o1\" channel=\"2\" loc=\"78\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r7\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r7_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_T\" value=\"1688.09\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r7_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r7_o1\" channel=\"2\" loc=\"74\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r8\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r8_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r8_T\" value=\"2126.71\"/>\n"
"\t \t \t <PARAM id=\"i0_r8_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r8_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r8_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r8_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r8_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r8_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r8_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r8_o1\" channel=\"2\" loc=\"67\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r9\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r9_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r9_T\" value=\"2679.62\"/>\n"
"\t \t \t <PARAM id=\"i0_r9_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r9_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r9_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r9_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r9_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r9_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r9_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r9_o1\" channel=\"2\" loc=\"60\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r10\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r10_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r10_T\" value=\"3007.76\"/>\n"
"\t \t \t <PARAM id=\"i0_r10_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r10_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r10_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r10_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r10_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r10_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r10_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r10_o1\" channel=\"2\" loc=\"57\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r11\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r11_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r11_T\" value=\"3789.58\"/>\n"
"\t \t \t <PARAM id=\"i0_r11_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r11_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r11_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r11_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r11_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r11_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r11_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r11_o1\" channel=\"2\" loc=\"51\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r12\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r12_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r12_T\" value=\"4774.47\"/>\n"
"\t \t \t <PARAM id=\"i0_r12_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r12_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r12_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r12_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r12_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r12_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r12_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r12_o1\" channel=\"2\" loc=\"45\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r13\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r13_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r13_T\" value=\"6015.37\"/>\n"
"\t \t \t <PARAM id=\"i0_r13_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r13_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r13_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r13_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r13_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r13_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r13_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r13_o1\" channel=\"2\" loc=\"40\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r14\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r14_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r14_T\" value=\"6752.09\"/>\n"
"\t \t \t <PARAM id=\"i0_r14_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r14_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r14_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r14_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r14_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r14_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r14_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r14_o1\" channel=\"2\" loc=\"37\"/>\n"
"\t \t </Resonator>\n"
"\t \t <ResonatorGroup id=\"i0_g0\">\n"
"\t \t \t <Res id=\"0\"/>\n"
"\t \t \t <Res id=\"1\"/>\n"
"\t \t </ResonatorGroup>\n"
"\t \t <ResonatorGroup id=\"i0_g1\">\n"
"\t \t \t <Res id=\"2\"/>\n"
"\t \t \t <Res id=\"3\"/>\n"
"\t \t </ResonatorGroup>\n"
"\t \t <ResonatorGroup id=\"i0_g2\">\n"
"\t \t \t <Res id=\"4\"/>\n"
"\t \t \t <Res id=\"5\"/>\n"
"\t \t \t <Res id=\"11\"/>\n"
"\t \t \t <Res id=\"13\"/>\n"
"\t \t </ResonatorGroup>\n"
"\t </Instrument>\n"
"</App>\n";

const char* HarpGroups_xml = (const char*) temp_binary_data_4;

//================== lastPreset.txt ==================
static const unsigned char temp_binary_data_5[] =
"TwoStrings.xml";

const char* lastPreset_txt = (const char*) temp_binary_data_5;

//================== lastSavedPreset.xml ==================
static const unsigned char temp_binary_data_6[] =
"<App>\n"
"\t <Instrument id=\"i0\">\n"
"\t \t <Resonator id=\"i0_r0\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r0_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_T\" value=\"669.864\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig1\" value=\"0.005\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r1\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r1_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_T\" value=\"1193.62\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_sig1\" value=\"0.005\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r2\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r2_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_T\" value=\"2126.71\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_sig1\" value=\"0.005\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r3\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r3_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_T\" value=\"3789.59\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_sig1\" value=\"0.005\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r4\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r4_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_T\" value=\"6015.37\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_sig1\" value=\"0.005\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r5\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r5_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_T\" value=\"10718.1\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_sig1\" value=\"0.005\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r6\" type=\"Bar\">\n"
"\t \t \t <PARAM id=\"i0_r6_L\" value=\"0.5\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_rho\" value=\"1190\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_A\" value=\"2.0175e-05\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_E\" value=\"3.2e+09\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_I\" value=\"9.45703e-11\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_sig1\" value=\"0.05\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r7\" type=\"Thin_Plate\">\n"
"\t \t \t <PARAM id=\"i0_r7_Lx\" value=\"0.75\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_Ly\" value=\"0.25\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_rho\" value=\"1150\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_H\" value=\"0.005\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_E\" value=\"3.8e+09\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_nu\" value=\"0.3\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_sig1\" value=\"0.05\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_maxPoints\" value=\"2000\"/>\n"
"\t \t \t <Output id=\"i0_r7_o0\" channel=\"2\" loc=\"237\"/>\n"
"\t \t \t <Output id=\"i0_r7_o1\" channel=\"2\" loc=\"425\"/>\n"
"\t \t \t <Output id=\"i0_r7_o2\" channel=\"2\" loc=\"566\"/>\n"
"\t \t \t <Output id=\"i0_r7_o3\" channel=\"2\" loc=\"614\"/>\n"
"\t \t \t <Output id=\"i0_r7_o4\" channel=\"2\" loc=\"616\"/>\n"
"\t \t \t <Output id=\"i0_r7_o5\" channel=\"2\" loc=\"570\"/>\n"
"\t \t \t <Output id=\"i0_r7_o6\" channel=\"2\" loc=\"335\"/>\n"
"\t \t \t <Output id=\"i0_r7_o7\" channel=\"2\" loc=\"194\"/>\n"
"\t \t \t <Output id=\"i0_r7_o8\" channel=\"2\" loc=\"99\"/>\n"
"\t \t \t <Output id=\"i0_r7_o9\" channel=\"2\" loc=\"98\"/>\n"
"\t \t \t <Output id=\"i0_r7_o10\" channel=\"2\" loc=\"97\"/>\n"
"\t \t \t <Output id=\"i0_r7_o11\" channel=\"2\" loc=\"144\"/>\n"
"\t \t \t <Output id=\"i0_r7_o12\" channel=\"2\" loc=\"238\"/>\n"
"\t \t \t <Output id=\"i0_r7_o13\" channel=\"2\" loc=\"332\"/>\n"
"\t \t \t <Output id=\"i0_r7_o14\" channel=\"2\" loc=\"426\"/>\n"
"\t \t \t <Output id=\"i0_r7_o15\" channel=\"2\" loc=\"473\"/>\n"
"\t \t \t <Output id=\"i0_r7_o16\" channel=\"2\" loc=\"567\"/>\n"
"\t \t \t <Output id=\"i0_r7_o17\" channel=\"2\" loc=\"430\"/>\n"
"\t \t \t <Output id=\"i0_r7_o18\" channel=\"2\" loc=\"476\"/>\n"
"\t \t \t <Output id=\"i0_r7_o19\" channel=\"2\" loc=\"382\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Connection id=\"i0_c0\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c0_fR\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_c0_fL\" value=\"88\"/>\n"
"\t \t \t <PARAM id=\"i0_c0_tR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c0_tL\" value=\"9\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c1\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c1_fR\" value=\"2\"/>\n"
"\t \t \t <PARAM id=\"i0_c1_fL\" value=\"70\"/>\n"
"\t \t \t <PARAM id=\"i0_c1_tR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c1_tL\" value=\"15\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c2\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c2_fR\" value=\"3\"/>\n"
"\t \t \t <PARAM id=\"i0_c2_fL\" value=\"54\"/>\n"
"\t \t \t <PARAM id=\"i0_c2_tR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c2_tL\" value=\"22\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c3\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c3_fR\" value=\"4\"/>\n"
"\t \t \t <PARAM id=\"i0_c3_fL\" value=\"43\"/>\n"
"\t \t \t <PARAM id=\"i0_c3_tR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c3_tL\" value=\"28\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c4\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c4_fR\" value=\"5\"/>\n"
"\t \t \t <PARAM id=\"i0_c4_fL\" value=\"32\"/>\n"
"\t \t \t <PARAM id=\"i0_c4_tR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c4_tL\" value=\"34\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c5\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c5_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c5_fL\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c5_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c5_tL\" value=\"240\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c6\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c6_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c6_fL\" value=\"10\"/>\n"
"\t \t \t <PARAM id=\"i0_c6_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c6_tL\" value=\"286\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c7\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c7_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c7_fL\" value=\"13\"/>\n"
"\t \t \t <PARAM id=\"i0_c7_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c7_tL\" value=\"334\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c8\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c8_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c8_fL\" value=\"24\"/>\n"
"\t \t \t <PARAM id=\"i0_c8_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c8_tL\" value=\"474\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c9\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c9_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c9_fL\" value=\"36\"/>\n"
"\t \t \t <PARAM id=\"i0_c9_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c9_tL\" value=\"616\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c10\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c10_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c10_fL\" value=\"32\"/>\n"
"\t \t \t <PARAM id=\"i0_c10_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c10_tL\" value=\"568\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c11\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c11_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c11_fL\" value=\"27\"/>\n"
"\t \t \t <PARAM id=\"i0_c11_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c11_tL\" value=\"522\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c12\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c12_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c12_fL\" value=\"20\"/>\n"
"\t \t \t <PARAM id=\"i0_c12_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c12_tL\" value=\"428\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c13\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c13_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c13_fL\" value=\"17\"/>\n"
"\t \t \t <PARAM id=\"i0_c13_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c13_tL\" value=\"380\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c14\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c14_fR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c14_fL\" value=\"4\"/>\n"
"\t \t \t <PARAM id=\"i0_c14_tR\" value=\"7\"/>\n"
"\t \t \t <PARAM id=\"i0_c14_tL\" value=\"192\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c15\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c15_fR\" value=\"0\"/>\n"
"\t \t \t <PARAM id=\"i0_c15_fL\" value=\"103\"/>\n"
"\t \t \t <PARAM id=\"i0_c15_tR\" value=\"6\"/>\n"
"\t \t \t <PARAM id=\"i0_c15_tL\" value=\"5\"/>\n"
"\t \t </Connection>\n"
"\t </Instrument>\n"
"</App>\n";

const char* lastSavedPreset_xml = (const char*) temp_binary_data_6;

//================== SanturUnedited.xml ==================
static const unsigned char temp_binary_data_7[] =
"<App>\n"
"\t <Instrument id=\"i0\">\n"
"\t \t <Resonator id=\"i0_r0\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r0_L\" value=\"0.73\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_T\" value=\"11800\"/>\n"
"\t\t\t <PARAM id=\"i0_r0_rho\" value=\"8400\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_A\" value=\"1.468729e-05\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_E\" value=\"1.135e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_I\" value=\"1.717487e-11\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig0\" value=\"1.14\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig1\" value=\"0.0006\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r1\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r1_L\" value=\"0.53\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_T\" value=\"39003\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_rho\" value=\"7700\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_A\" value=\"1.539445e-05\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_E\" value=\"1.8e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_sig0\" value=\"1.14\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_sig1\" value=\"0.0006\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r2\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r2_L\" value=\"0.69\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_T\" value=\"16079\"/>\n"
"\t\t\t <PARAM id=\"i0_r0_rho\" value=\"8400\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_A\" value=\"1.620527e-05\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_E\" value=\"1.135e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_sig0\" value=\"1.14\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_sig1\" value=\"0.0006\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r3\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r3_L\" value=\"0.5\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_T\" value=\"68503\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_rho\" value=\"7700\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_A\" value=\"1.924705e-05\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_E\" value=\"1.8e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_sig0\" value=\"1.14\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_sig1\" value=\"0.0006\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r4\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r4_L\" value=\"0.64\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_T\" value=\"22079\"/>\n"
"\t\t\t <PARAM id=\"i0_r0_rho\" value=\"8400\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_A\" value=\"1.761357e-05\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_E\" value=\"1.135e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_sig0\" value=\"1.14\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_sig1\" value=\"0.0006\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r5\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r5_L\" value=\"0.48\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_T\" value=\"98926\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_rho\" value=\"7700\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_A\" value=\"2.220424e-05\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_E\" value=\"1.8e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_sig0\" value=\"1.14\"/>\n"
"\t \t \t <PARAM id=\"i0_r5_sig1\" value=\"0.0006\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r6\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r6_L\" value=\"0.59\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_T\" value=\"29772\"/>\n"
"\t\t\t <PARAM id=\"i0_r0_rho\" value=\"8400\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_A\" value=\"1.885531e-05\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_E\" value=\"1.135e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_sig0\" value=\"1.14\"/>\n"
"\t \t \t <PARAM id=\"i0_r6_sig1\" value=\"0.0006\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r7\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r7_L\" value=\"0.45\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_T\" value=\"138692\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_rho\" value=\"7700\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_A\" value=\"2.464777e-05\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_E\" value=\"1.8e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_sig0\" value=\"1.14\"/>\n"
"\t \t \t <PARAM id=\"i0_r7_sig1\" value=\"0.0006\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r8\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r8_L\" value=\"0.54\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_T\" value=\"31010\"/>\n"
"\t\t\t <PARAM id=\"i0_r0_rho\" value=\"8400\"/>\n"
"\t \t \t <PARAM id=\"i0_r8_A\" value=\"1.761256e-05\"/>\n"
"\t \t \t <PARAM id=\"i0_r8_E\" value=\"1.135e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r8_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r8_sig0\" value=\"1.14\"/>\n"
"\t \t \t <PARAM id=\"i0_r8_sig1\" value=\"0.0006\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r9\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r9_L\" value=\"0.42\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_T\" value=\"147464\"/>\n"
"\t\t\t <PARAM id=\"i0_r0_rho\" value=\"7700\"/>\n"
"\t \t \t <PARAM id=\"i0_r9_A\" value=\"2.372093e-05\"/>\n"
"\t \t \t <PARAM id=\"i0_r9_E\" value=\"1.8e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r9_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r9_sig0\" value=\"1.14\"/>\n"
"\t \t \t <PARAM id=\"i0_r9_sig1\" value=\"0.0006\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r10\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r10_L\" value=\"0.5\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_T\" value=\"42466\"/>\n"
"\t\t\t <PARAM id=\"i0_r0_rho\" value=\"8400\"/>\n"
"\t \t \t <PARAM id=\"i0_r10_A\" value=\"1.908396e-05\"/>\n"
"\t \t \t <PARAM id=\"i0_r10_E\" value=\"1.135e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r10_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r10_sig0\" value=\"1.14\"/>\n"
"\t \t \t <PARAM id=\"i0_r10_sig1\" value=\"0.0006\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r11\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r11_L\" value=\"0.39\"/>\n"
"\t \t \t <PARAM id=\"i0_r11_T\" value=\"200700\"/>\n"
"\t \t \t <PARAM id=\"i0_r11_rho\" value=\"7700\"/>\n"
"\t \t \t <PARAM id=\"i0_r11_A\" value=\"2.569672e-05\"/>\n"
"\t \t \t <PARAM id=\"i0_r11_E\" value=\"1.8e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r11_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r11_sig0\" value=\"1.14\"/>\n"
"\t \t \t <PARAM id=\"i0_r11_sig1\" value=\"0.0006\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r12\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r12_L\" value=\"0.45\"/>\n"
"\t \t \t <PARAM id=\"i0_r12_T\" value=\"54010\"/>\n"
"\t \t \t <PARAM id=\"i0_r12_rho\" value=\"8400\"/>\n"
"\t \t \t <PARAM id=\"i0_r12_A\" value=\"1.936990e-05\"/>\n"
"\t \t \t <PARAM id=\"i0_r12_E\" value=\"1.135e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r12_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r12_sig0\" value=\"1.14\"/>\n"
"\t \t \t <PARAM id=\"i0_r12_sig1\" value=\"0.0006\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r13\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r13_L\" value=\"0.36\"/>\n"
"\t \t \t <PARAM id=\"i0_r13_T\" value=\"263315\"/>\n"
"\t \t \t <PARAM id=\"i0_r13_rho\" value=\"7700\"/>\n"
"\t \t \t <PARAM id=\"i0_r13_A\" value=\"2.716938e-05\"/>\n"
"\t \t \t <PARAM id=\"i0_r13_E\" value=\"1.8e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r13_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r13_sig0\" value=\"1.14\"/>\n"
"\t \t \t <PARAM id=\"i0_r13_sig1\" value=\"0.0006\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r14\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r14_L\" value=\"0.4\"/>\n"
"\t \t \t <PARAM id=\"i0_r14_T\" value=\"53351\"/>\n"
"\t \t \t <PARAM id=\"i0_r14_rho\" value=\"8400\"/>\n"
"\t \t \t <PARAM id=\"i0_r14_A\" value=\"1.711232e-05\"/>\n"
"\t \t \t <PARAM id=\"i0_r14_E\" value=\"1.135e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r14_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r14_sig0\" value=\"1.14\"/>\n"
"\t \t \t <PARAM id=\"i0_r14_sig1\" value=\"0.0006\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r15\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r15_L\" value=\"0.33\"/>\n"
"\t \t \t <PARAM id=\"i0_r15_T\" value=\"273722\"/>\n"
"\t \t \t <PARAM id=\"i0_r15_rho\" value=\"7700\"/>\n"
"\t \t \t <PARAM id=\"i0_r15_A\" value=\"2.539266e-05\"/>\n"
"\t \t \t <PARAM id=\"i0_r15_E\" value=\"1.8e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r15_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r15_sig0\" value=\"1.14\"/>\n"
"\t \t \t <PARAM id=\"i0_r15_sig1\" value=\"0.0006\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r16\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r16_L\" value=\"0.34\"/>\n"
"\t \t \t <PARAM id=\"i0_r16_T\" value=\"60384\"/>\n"
"\t \t \t <PARAM id=\"i0_r16_rho\" value=\"8400\"/>\n"
"\t \t \t <PARAM id=\"i0_r16_A\" value=\"1.547453e-05\"/>\n"
"\t \t \t <PARAM id=\"i0_r16_E\" value=\"1.135e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r16_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r16_sig0\" value=\"1.14\"/>\n"
"\t \t \t <PARAM id=\"i0_r16_sig1\" value=\"0.0006\"/>\n"
"\t \t </Resonator>\n"
"\t\t <Resonator id=\"i0_r17\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r17_L\" value=\"0.3\"/>\n"
"\t \t \t <PARAM id=\"i0_r17_T\" value=\"352863\"/>\n"
"\t \t \t <PARAM id=\"i0_r17_rho\" value=\"7700\"/>\n"
"\t \t \t <PARAM id=\"i0_r17_A\" value=\"2.620980e-05\"/>\n"
"\t \t \t <PARAM id=\"i0_r17_E\" value=\"1.8e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r17_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r17_sig0\" value=\"1.14\"/>\n"
"\t \t \t <PARAM id=\"i0_r17_sig1\" value=\"0.0006\"/>\n"
"\t \t </Resonator>\n"
"\t </Instrument>\n"
"</App>\n";

const char* SanturUnedited_xml = (const char*) temp_binary_data_7;

//================== Shamisen.xml ==================
static const unsigned char temp_binary_data_8[] =
"<App>\n"
"\t <Instrument id=\"i0\">\n"
"\t \t <Resonator id=\"i0_r0\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r0_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_T\" value=\"138.67\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_rho\" value=\"1156\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_A\" value=\"5.41e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_E\" value=\"9.9e+09\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_I\" value=\"2.3296e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig0\" value=\"1.378\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig1\" value=\"0.00357\"/>\n"
"\t \t \t <Output id=\"i0_r0_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r0_o1\" channel=\"2\" loc=\"94\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r1\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r1_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_T\" value=\"145.53\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_rho\" value=\"1156\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_A\" value=\"2.52e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_E\" value=\"9.9e+09\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_I\" value=\"5.03774e-15\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_sig0\" value=\"1.378\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_sig1\" value=\"0.00357\"/>\n"
"\t \t \t <Output id=\"i0_r1_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r1_o1\" channel=\"2\" loc=\"63\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r2\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r2_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_T\" value=\"140.73\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_rho\" value=\"1156\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_A\" value=\"1.39e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_E\" value=\"9.9e+09\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_I\" value=\"1.52745e-15\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_sig0\" value=\"1.378\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_sig1\" value=\"0.00357\"/>\n"
"\t \t \t <Output id=\"i0_r2_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r2_o1\" channel=\"2\" loc=\"47\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r3\" type=\"Bar\">\n"
"\t \t \t <PARAM id=\"i0_r3_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_rho\" value=\"500\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_A\" value=\"2.0175e-05\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_E\" value=\"9.5e+09\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_I\" value=\"9.45703e-11\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_sig0\" value=\"1.343\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_sig1\" value=\"0.0759\"/>\n"
"\t \t \t <Output id=\"i0_r3_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r3_o1\" channel=\"2\" loc=\"46\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r4\" type=\"Stiff_Membrane\">\n"
"\t \t \t <PARAM id=\"i0_r4_Lx\" value=\"0.3\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_Ly\" value=\"0.4\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_rho\" value=\"1150\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_H\" value=\"0.0002\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_T\" value=\"400\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_E\" value=\"3e+09\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_nu\" value=\"0.3\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_sig0\" value=\"2.756\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_sig1\" value=\"0.192\"/>\n"
"\t \t \t <PARAM id=\"i0_r4_maxPoints\" value=\"2000\"/>\n"
"\t \t \t <Output id=\"i0_r4_o0\" channel=\"0\" loc=\"195\"/>\n"
"\t \t \t <Output id=\"i0_r4_o1\" channel=\"1\" loc=\"223\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Connection id=\"i0_c0\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c0_fR\" value=\"0\"/>\n"
"\t \t \t <PARAM id=\"i0_c0_fL\" value=\"18\"/>\n"
"\t \t \t <PARAM id=\"i0_c0_tR\" value=\"3\"/>\n"
"\t \t \t <PARAM id=\"i0_c0_tL\" value=\"11\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c1\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c1_fR\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_c1_fL\" value=\"12\"/>\n"
"\t \t \t <PARAM id=\"i0_c1_tR\" value=\"3\"/>\n"
"\t \t \t <PARAM id=\"i0_c1_tL\" value=\"24\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c2\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c2_fR\" value=\"2\"/>\n"
"\t \t \t <PARAM id=\"i0_c2_fL\" value=\"9\"/>\n"
"\t \t \t <PARAM id=\"i0_c2_tR\" value=\"3\"/>\n"
"\t \t \t <PARAM id=\"i0_c2_tL\" value=\"37\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c3\" type=\"nonlinear\">\n"
"\t \t \t <PARAM id=\"i0_c3_fR\" value=\"3\"/>\n"
"\t \t \t <PARAM id=\"i0_c3_fL\" value=\"5\"/>\n"
"\t \t \t <PARAM id=\"i0_c3_tR\" value=\"4\"/>\n"
"\t \t \t <PARAM id=\"i0_c3_tL\" value=\"791\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c4\" type=\"nonlinear\">\n"
"\t \t \t <PARAM id=\"i0_c4_fR\" value=\"3\"/>\n"
"\t \t \t <PARAM id=\"i0_c4_fL\" value=\"43\"/>\n"
"\t \t \t <PARAM id=\"i0_c4_tR\" value=\"4\"/>\n"
"\t \t \t <PARAM id=\"i0_c4_tL\" value=\"1437\"/>\n"
"\t \t </Connection>\n"
"\t </Instrument>\n"
"</App>\n";

const char* Shamisen_xml = (const char*) temp_binary_data_8;

//================== SimpleString.xml ==================
static const unsigned char temp_binary_data_9[] =
"<App>\n"
"\t <Instrument id=\"i0\">\n"
"\t \t <Resonator id=\"i0_r0\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r0_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_T\" value=\"300\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r0_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r0_o1\" channel=\"2\" loc=\"114\"/>\n"
"\t \t </Resonator>\n"
"\t </Instrument>\n"
"</App>\n";

const char* SimpleString_xml = (const char*) temp_binary_data_9;

//================== TwoStrings.xml ==================
static const unsigned char temp_binary_data_10[] =
"<App>\n"
"\t <Instrument id=\"i0\">\n"
"\t \t <Resonator id=\"i0_r0\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r0_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_T\" value=\"246.615\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r0_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r0_o1\" channel=\"2\" loc=\"116\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r1\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r1_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_T\" value=\"986.46\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r1_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r1_o1\" channel=\"2\" loc=\"90\"/>\n"
"\t \t </Resonator>\n"
"\t </Instrument>\n"
"</App>\n";

const char* TwoStrings_xml = (const char*) temp_binary_data_10;

//================== Ukulele.xml ==================
static const unsigned char temp_binary_data_11[] =
"<App>\n"
"\t <Instrument id=\"i0\">\n"
"\t \t <Resonator id=\"i0_r0\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r0_L\" value=\"0.6604\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_T\" value=\"100\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_rho\" value=\"1140\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_A\" value=\"1.2668e-06\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_E\" value=\"1e+09\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_I\" value=\"1.277e-13\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r0_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r0_o1\" channel=\"2\" loc=\"99\"/>\n"
"\t \t </Resonator>\n"
"\t </Instrument>\n"
"</App>\n";

const char* Ukulele_xml = (const char*) temp_binary_data_11;

//================== WeirdInstrument.xml ==================
static const unsigned char temp_binary_data_12[] =
"<App>\n"
"\t <Instrument id=\"i0\">\n"
"\t \t <Resonator id=\"i0_r0\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r0_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_T\" value=\"669.864\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r0_o0\" channel=\"2\" loc=\"100\"/>\n"
"\t \t \t <Output id=\"i0_r0_o1\" channel=\"2\" loc=\"4\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r1\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r1_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_T\" value=\"1193.62\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r1_o0\" channel=\"2\" loc=\"6\"/>\n"
"\t \t \t <Output id=\"i0_r1_o1\" channel=\"2\" loc=\"84\"/>\n"
"\t \t \t <Output id=\"i0_r1_o2\" channel=\"2\" loc=\"61\"/>\n"
"\t \t \t <Output id=\"i0_r1_o3\" channel=\"2\" loc=\"52\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r2\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r2_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_T\" value=\"29998\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_A\" value=\"7.85398e-05\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_I\" value=\"4.90874e-10\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r2_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r2_o1\" channel=\"2\" loc=\"37\"/>\n"
"\t \t \t <Output id=\"i0_r2_o2\" channel=\"2\" loc=\"28\"/>\n"
"\t \t \t <Output id=\"i0_r2_o3\" channel=\"2\" loc=\"20\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r3\" type=\"Thin_Plate\">\n"
"\t \t \t <PARAM id=\"i0_r3_Lx\" value=\"0.75\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_Ly\" value=\"0.25\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_H\" value=\"0.005\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_nu\" value=\"0.3\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_sig1\" value=\"0.005\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_maxPoints\" value=\"2000\"/>\n"
"\t \t \t <Output id=\"i0_r3_o0\" channel=\"0\" loc=\"145\"/>\n"
"\t \t \t <Output id=\"i0_r3_o1\" channel=\"1\" loc=\"163\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Connection id=\"i0_c0\" type=\"nonlinear\">\n"
"\t \t \t <PARAM id=\"i0_c0_fR\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_c0_fL\" value=\"50\"/>\n"
"\t \t \t <PARAM id=\"i0_c0_tR\" value=\"2\"/>\n"
"\t \t \t <PARAM id=\"i0_c0_tL\" value=\"18\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c1\" type=\"nonlinear\">\n"
"\t \t \t <PARAM id=\"i0_c1_fR\" value=\"0\"/>\n"
"\t \t \t <PARAM id=\"i0_c1_fL\" value=\"37\"/>\n"
"\t \t \t <PARAM id=\"i0_c1_tR\" value=\"2\"/>\n"
"\t \t \t <PARAM id=\"i0_c1_tL\" value=\"25\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c2\" type=\"nonlinear\">\n"
"\t \t \t <PARAM id=\"i0_c2_fR\" value=\"0\"/>\n"
"\t \t \t <PARAM id=\"i0_c2_fL\" value=\"25\"/>\n"
"\t \t \t <PARAM id=\"i0_c2_tR\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_c2_tL\" value=\"64\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c3\" type=\"nonlinear\">\n"
"\t \t \t <PARAM id=\"i0_c3_fR\" value=\"0\"/>\n"
"\t \t \t <PARAM id=\"i0_c3_fL\" value=\"65\"/>\n"
"\t \t \t <PARAM id=\"i0_c3_tR\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_c3_tL\" value=\"20\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c4\" type=\"nonlinear\">\n"
"\t \t \t <PARAM id=\"i0_c4_fR\" value=\"2\"/>\n"
"\t \t \t <PARAM id=\"i0_c4_fL\" value=\"22\"/>\n"
"\t \t \t <PARAM id=\"i0_c4_tR\" value=\"3\"/>\n"
"\t \t \t <PARAM id=\"i0_c4_tL\" value=\"151\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c5\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c5_fR\" value=\"2\"/>\n"
"\t \t \t <PARAM id=\"i0_c5_fL\" value=\"30\"/>\n"
"\t \t \t <PARAM id=\"i0_c5_tR\" value=\"3\"/>\n"
"\t \t \t <PARAM id=\"i0_c5_tL\" value=\"190\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c6\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c6_fR\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_c6_fL\" value=\"71\"/>\n"
"\t \t \t <PARAM id=\"i0_c6_tR\" value=\"2\"/>\n"
"\t \t \t <PARAM id=\"i0_c6_tL\" value=\"27\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c7\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c7_fR\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_c7_fL\" value=\"57\"/>\n"
"\t \t \t <PARAM id=\"i0_c7_tR\" value=\"3\"/>\n"
"\t \t \t <PARAM id=\"i0_c7_tL\" value=\"158\"/>\n"
"\t \t </Connection>\n"
"\t </Instrument>\n"
"</App>\n";

const char* WeirdInstrument_xml = (const char*) temp_binary_data_12;

//================== WeirdInstrument2.xml ==================
static const unsigned char temp_binary_data_13[] =
"<App>\n"
"\t <Instrument id=\"i0\">\n"
"\t \t <Resonator id=\"i0_r0\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r0_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_T\" value=\"669.864\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r0_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r0_o0\" channel=\"2\" loc=\"100\"/>\n"
"\t \t \t <Output id=\"i0_r0_o1\" channel=\"2\" loc=\"4\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r1\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r1_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_T\" value=\"1193.62\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_A\" value=\"7.85398e-07\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_I\" value=\"4.90874e-14\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r1_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r1_o0\" channel=\"2\" loc=\"6\"/>\n"
"\t \t \t <Output id=\"i0_r1_o1\" channel=\"2\" loc=\"84\"/>\n"
"\t \t \t <Output id=\"i0_r1_o2\" channel=\"2\" loc=\"61\"/>\n"
"\t \t \t <Output id=\"i0_r1_o3\" channel=\"2\" loc=\"52\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r2\" type=\"Stiff_String\">\n"
"\t \t \t <PARAM id=\"i0_r2_L\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_T\" value=\"29998\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_A\" value=\"7.85398e-05\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_I\" value=\"4.90874e-10\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r2_sig1\" value=\"0.005\"/>\n"
"\t \t \t <Output id=\"i0_r2_o0\" channel=\"2\" loc=\"4\"/>\n"
"\t \t \t <Output id=\"i0_r2_o1\" channel=\"2\" loc=\"37\"/>\n"
"\t \t \t <Output id=\"i0_r2_o2\" channel=\"2\" loc=\"28\"/>\n"
"\t \t \t <Output id=\"i0_r2_o3\" channel=\"2\" loc=\"20\"/>\n"
"\t \t \t <Output id=\"i0_r2_o4\" channel=\"2\" loc=\"35\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Resonator id=\"i0_r3\" type=\"Thin_Plate\">\n"
"\t \t \t <PARAM id=\"i0_r3_Lx\" value=\"0.75\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_Ly\" value=\"0.25\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_rho\" value=\"7850\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_H\" value=\"0.005\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_E\" value=\"2e+11\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_nu\" value=\"0.3\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_sig0\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_sig1\" value=\"0.005\"/>\n"
"\t \t \t <PARAM id=\"i0_r3_maxPoints\" value=\"2000\"/>\n"
"\t \t \t <Output id=\"i0_r3_o0\" channel=\"0\" loc=\"145\"/>\n"
"\t \t \t <Output id=\"i0_r3_o1\" channel=\"1\" loc=\"163\"/>\n"
"\t \t </Resonator>\n"
"\t \t <Connection id=\"i0_c0\" type=\"nonlinear\">\n"
"\t \t \t <PARAM id=\"i0_c0_fR\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_c0_fL\" value=\"50\"/>\n"
"\t \t \t <PARAM id=\"i0_c0_tR\" value=\"2\"/>\n"
"\t \t \t <PARAM id=\"i0_c0_tL\" value=\"18\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c1\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c1_fR\" value=\"0\"/>\n"
"\t \t \t <PARAM id=\"i0_c1_fL\" value=\"37\"/>\n"
"\t \t \t <PARAM id=\"i0_c1_tR\" value=\"2\"/>\n"
"\t \t \t <PARAM id=\"i0_c1_tL\" value=\"14\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c2\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c2_fR\" value=\"0\"/>\n"
"\t \t \t <PARAM id=\"i0_c2_fL\" value=\"73\"/>\n"
"\t \t \t <PARAM id=\"i0_c2_tR\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_c2_tL\" value=\"64\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c3\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c3_fR\" value=\"0\"/>\n"
"\t \t \t <PARAM id=\"i0_c3_fL\" value=\"65\"/>\n"
"\t \t \t <PARAM id=\"i0_c3_tR\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_c3_tL\" value=\"55\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c4\" type=\"nonlinear\">\n"
"\t \t \t <PARAM id=\"i0_c4_fR\" value=\"2\"/>\n"
"\t \t \t <PARAM id=\"i0_c4_fL\" value=\"22\"/>\n"
"\t \t \t <PARAM id=\"i0_c4_tR\" value=\"3\"/>\n"
"\t \t \t <PARAM id=\"i0_c4_tL\" value=\"151\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c5\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c5_fR\" value=\"2\"/>\n"
"\t \t \t <PARAM id=\"i0_c5_fL\" value=\"30\"/>\n"
"\t \t \t <PARAM id=\"i0_c5_tR\" value=\"3\"/>\n"
"\t \t \t <PARAM id=\"i0_c5_tL\" value=\"190\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c6\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c6_fR\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_c6_fL\" value=\"71\"/>\n"
"\t \t \t <PARAM id=\"i0_c6_tR\" value=\"2\"/>\n"
"\t \t \t <PARAM id=\"i0_c6_tL\" value=\"27\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c7\" type=\"rigid\">\n"
"\t \t \t <PARAM id=\"i0_c7_fR\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_c7_fL\" value=\"57\"/>\n"
"\t \t \t <PARAM id=\"i0_c7_tR\" value=\"3\"/>\n"
"\t \t \t <PARAM id=\"i0_c7_tL\" value=\"158\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c8\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c8_fR\" value=\"0\"/>\n"
"\t \t \t <PARAM id=\"i0_c8_fL\" value=\"28\"/>\n"
"\t \t \t <PARAM id=\"i0_c8_tR\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_c8_tL\" value=\"24\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c9\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c9_fR\" value=\"0\"/>\n"
"\t \t \t <PARAM id=\"i0_c9_fL\" value=\"83\"/>\n"
"\t \t \t <PARAM id=\"i0_c9_tR\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_c9_tL\" value=\"74\"/>\n"
"\t \t </Connection>\n"
"\t \t <Connection id=\"i0_c10\" type=\"linear\">\n"
"\t \t \t <PARAM id=\"i0_c10_fR\" value=\"0\"/>\n"
"\t \t \t <PARAM id=\"i0_c10_fL\" value=\"16\"/>\n"
"\t \t \t <PARAM id=\"i0_c10_tR\" value=\"1\"/>\n"
"\t \t \t <PARAM id=\"i0_c10_tL\" value=\"14\"/>\n"
"\t \t </Connection>\n"
"\t </Instrument>\n"
"</App>\n";

const char* WeirdInstrument2_xml = (const char*) temp_binary_data_13;

//================== LICENSE ==================
static const unsigned char temp_binary_data_14[] =
"MIT License\n"
"\n"
"Copyright (c) 2018 SMC-AAU-CPH\n"
"\n"
"Permission is hereby granted, free of charge, to any person obtaining a copy\n"
"of this software and associated documentation files (the \"Software\"), to deal\n"
"in the Software without restriction, including without limitation the rights\n"
"to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
"copies of the Software, and to permit persons to whom the Software is\n"
"furnished to do so, subject to the following conditions:\n"
"\n"
"The above copyright notice and this permission notice shall be included in all\n"
"copies or substantial portions of the Software.\n"
"\n"
"THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
"AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
"LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
"OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n"
"SOFTWARE.\n";

const char* LICENSE = (const char*) temp_binary_data_14;

//================== README.md ==================
static const unsigned char temp_binary_data_15[] =
"# SenselWrapper\n"
"Simple wrapper for Sensel Morph API to make it easier to integrate in C++ projects. \n"
"\n"
"\n"
"Link to [Sensel API](https://github.com/sensel/sensel-api).\n"
"\n"
"\n"
"A simple JUCE project using the sensel can be found in the [test branch](https://github.com/SMC-AAU-CPH/SenselWrapper/tree/test).\n";

const char* README_md = (const char*) temp_binary_data_15;


const char* getNamedResource (const char* resourceNameUTF8, int& numBytes);
const char* getNamedResource (const char* resourceNameUTF8, int& numBytes)
{
    unsigned int hash = 0;

    if (resourceNameUTF8 != nullptr)
        while (*resourceNameUTF8 != 0)
            hash = 31 * hash + (unsigned int) *resourceNameUTF8++;

    switch (hash)
    {
        case 0x5317664c:  numBytes = 52; return EmptyInstrument_xml;
        case 0x4c7b0ae2:  numBytes = 7272; return guitar_xml;
        case 0xf9dcf6d8:  numBytes = 4805; return GuitarWithoutBody_xml;
        case 0x0b70d0ef:  numBytes = 7820; return Harp_xml;
        case 0x3b83afa3:  numBytes = 8148; return HarpGroups_xml;
        case 0x653df846:  numBytes = 14; return lastPreset_txt;
        case 0x5b264f28:  numBytes = 7904; return lastSavedPreset_xml;
        case 0x7a248f4b:  numBytes = 7706; return SanturUnedited_xml;
        case 0xbdd4f18c:  numBytes = 3768; return Shamisen_xml;
        case 0x984b4a5b:  numBytes = 563; return SimpleString_xml;
        case 0x5c291b0e:  numBytes = 1080; return TwoStrings_xml;
        case 0xbdc45489:  numBytes = 564; return Ukulele_xml;
        case 0x4dbaafcc:  numBytes = 4109; return WeirdInstrument_xml;
        case 0x6715f496:  numBytes = 4810; return WeirdInstrument2_xml;
        case 0x34bc1021:  numBytes = 1068; return LICENSE;
        case 0x64791dc8:  numBytes = 295; return README_md;
        default: break;
    }

    numBytes = 0;
    return nullptr;
}

const char* namedResourceList[] =
{
    "EmptyInstrument_xml",
    "guitar_xml",
    "GuitarWithoutBody_xml",
    "Harp_xml",
    "HarpGroups_xml",
    "lastPreset_txt",
    "lastSavedPreset_xml",
    "SanturUnedited_xml",
    "Shamisen_xml",
    "SimpleString_xml",
    "TwoStrings_xml",
    "Ukulele_xml",
    "WeirdInstrument_xml",
    "WeirdInstrument2_xml",
    "LICENSE",
    "README_md"
};

const char* originalFilenames[] =
{
    "EmptyInstrument.xml",
    "guitar.xml",
    "GuitarWithoutBody.xml",
    "Harp.xml",
    "HarpGroups.xml",
    "lastPreset.txt",
    "lastSavedPreset.xml",
    "SanturUnedited.xml",
    "Shamisen.xml",
    "SimpleString.xml",
    "TwoStrings.xml",
    "Ukulele.xml",
    "WeirdInstrument.xml",
    "WeirdInstrument2.xml",
    "LICENSE",
    "README.md"
};

const char* getNamedResourceOriginalFilename (const char* resourceNameUTF8);
const char* getNamedResourceOriginalFilename (const char* resourceNameUTF8)
{
    for (unsigned int i = 0; i < (sizeof (namedResourceList) / sizeof (namedResourceList[0])); ++i)
    {
        if (namedResourceList[i] == resourceNameUTF8)
            return originalFilenames[i];
    }

    return nullptr;
}

}
